In [1]:
import pandas as pd

C:\Users\Hp\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\Hp\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [6]:
# import dataset
data=pd.read_csv('SalesData.csv')
data.head()

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
0,1.0,01-Jan-2010,37.0,Black Friday,Cash,Ramzan,UAE,Dubai,Mobile,1200.0,3.0,3600.0,200.0
1,2.0,02-Jan-2010,40.0,Chrismas Coupon,Visa Card,Kumayl,India,Abu Dhabi,Laptop,4500.0,2.0,9000.0,250.0
2,3.0,03-Jan-2010,36.0,Loyalty Coupon,Master Card,John,Oman,NaN,Moniter,3000.0,2.0,6000.0,300.0
3,4.0,03-Jan-2010,46.0,Black Friday,Stripe,Abdullah,UAE,NaN,Speaker,75.0,1.0,75.0,15.0
4,5.0,03-Jan-2010,24.0,Chrismas Coupon,Cheque,David,India,NaN,Keyboard,100.0,3.0,300.0,10.0

In [7]:
data.isnull().sum()

No                   4
Transaction Date     4
Customer Age         4
Coupon Type          4
Payment Method       6
Sales Person        12
Country              4
City                 7
Product             22
Price                4
Units                4
Sales                4
Profit               4
dtype: int64

In [9]:
data.tail()

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
4270,4267.0,26-Aug-2021,63.0,Black Friday,Visa Card,Abdullah,UAE,Muscat,Mobile,1200.0,2.0,2400.0,200.0
4271,4268.0,26-Aug-2021,64.0,Chrismas Coupon,Master Card,David,India,Salalah,Laptop,4500.0,3.0,13500.0,250.0
4272,4269.0,26-Aug-2021,27.0,Loyalty Coupon,Stripe,Nancy,Oman,Muscat,Moniter,3000.0,3.0,9000.0,300.0
4273,4270.0,26-Aug-2021,20.0,Black Friday,Cheque,Raj,UAE,Salalah,Speaker,75.0,1.0,75.0,15.0
4274,4271.0,26-Aug-2021,35.0,Chrismas Coupon,Cash,Ramzan,India,Muscat,Keyboard,100.0,1.0,100.0,10.0

In [10]:
data.shape

(4275, 13)

In [11]:
data.describe()

,No,Customer Age,Price,Units,Sales,Profit
count,4271.000000,4271.000000,4271.000000,4271.000000,4271.000000,4271.000000
mean,2136.000000,43.857645,1525.292672,1.781316,2718.982674,122.111918
std,1233.075829,15.303514,1828.106232,0.814642,3803.546789,111.304749
min,1.000000,18.000000,50.000000,1.000000,50.000000,5.000000
25%,1068.500000,31.000000,100.000000,1.000000,150.000000,15.000000
50%,2136.000000,44.000000,175.000000,2.000000,350.000000,50.000000
75%,3203.500000,57.000000,3000.000000,2.000000,4500.000000,225.000000
max,4271.000000,70.000000,4500.000000,3.000000,13500.000000,300.000000

In [13]:
# find data types of every column
data.dtypes

No                  float64
Transaction Date     object
Customer Age        float64
Coupon Type          object
Payment Method       object
Sales Person         object
Country              object
City                 object
Product              object
Price               float64
Units               float64
Sales               float64
Profit              float64
dtype: object

In [14]:
#Handling missing values
data.isnull()

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,False,False,False,False,False,False,False,False,False,False,False,False,False
4271,False,False,False,False,False,False,False,False,False,False,False,False,False
4272,False,False,False,False,False,False,False,False,False,False,False,False,False
4273,False,False,False,False,False,False,False,False,False,False,False,False,False
4274,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
data[data.isnull()]

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4273,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
data.isnull().any(axis=1)

0       False
1       False
2        True
3        True
4        True
        ...
4270    False
4271    False
4272    False
4273    False
4274    False
Length: 4275, dtype: bool

In [18]:
data.isnull().any()

No                  True
Transaction Date    True
Customer Age        True
Coupon Type         True
Payment Method      True
Sales Person        True
Country             True
City                True
Product             True
Price               True
Units               True
Sales               True
Profit              True
dtype: bool

In [19]:
data.isnull().sum()

No                   4
Transaction Date     4
Customer Age         4
Coupon Type          4
Payment Method       6
Sales Person        12
Country              4
City                 7
Product             22
Price                4
Units                4
Sales                4
Profit               4
dtype: int64

In [23]:
data.fillna(0)

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
0,1.0,01-Jan-2010,37.0,Black Friday,Cash,Ramzan,UAE,Dubai,Mobile,1200.0,3.0,3600.0,200.0
1,2.0,02-Jan-2010,40.0,Chrismas Coupon,Visa Card,Kumayl,India,Abu Dhabi,Laptop,4500.0,2.0,9000.0,250.0
2,3.0,03-Jan-2010,36.0,Loyalty Coupon,Master Card,John,Oman,0,Moniter,3000.0,2.0,6000.0,300.0
3,4.0,03-Jan-2010,46.0,Black Friday,Stripe,Abdullah,UAE,0,Speaker,75.0,1.0,75.0,15.0
4,5.0,03-Jan-2010,24.0,Chrismas Coupon,Cheque,David,India,0,Keyboard,100.0,3.0,300.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,4267.0,26-Aug-2021,63.0,Black Friday,Visa Card,Abdullah,UAE,Muscat,Mobile,1200.0,2.0,2400.0,200.0
4271,4268.0,26-Aug-2021,64.0,Chrismas Coupon,Master Card,David,India,Salalah,Laptop,4500.0,3.0,13500.0,250.0
4272,4269.0,26-Aug-2021,27.0,Loyalty Coupon,Stripe,Nancy,Oman,Muscat,Moniter,3000.0,3.0,9000.0,300.0
4273,4270.0,26-Aug-2021,20.0,Black Friday,Cheque,Raj,UAE,Salalah,Speaker,75.0,1.0,75.0,15.0
4274,4271.0,26-Aug-2021,35.0,Chrismas Coupon,Cash,Ramzan,India,Muscat,Keyboard,100.0,1.0,100.0,10.0

In [26]:
data

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit
0,1.0,01-Jan-2010,37.0,Black Friday,Cash,Ramzan,UAE,Dubai,Mobile,1200.0,3.0,3600.0,200.0
1,2.0,02-Jan-2010,40.0,Chrismas Coupon,Visa Card,Kumayl,India,Abu Dhabi,Laptop,4500.0,2.0,9000.0,250.0
2,3.0,03-Jan-2010,36.0,Loyalty Coupon,Master Card,John,Oman,NaN,Moniter,3000.0,2.0,6000.0,300.0
3,4.0,03-Jan-2010,46.0,Black Friday,Stripe,Abdullah,UAE,NaN,Speaker,75.0,1.0,75.0,15.0
4,5.0,03-Jan-2010,24.0,Chrismas Coupon,Cheque,David,India,NaN,Keyboard,100.0,3.0,300.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,4267.0,26-Aug-2021,63.0,Black Friday,Visa Card,Abdullah,UAE,Muscat,Mobile,1200.0,2.0,2400.0,200.0
4271,4268.0,26-Aug-2021,64.0,Chrismas Coupon,Master Card,David,India,Salalah,Laptop,4500.0,3.0,13500.0,250.0
4272,4269.0,26-Aug-2021,27.0,Loyalty Coupon,Stripe,Nancy,Oman,Muscat,Moniter,3000.0,3.0,9000.0,300.0
4273,4270.0,26-Aug-2021,20.0,Black Friday,Cheque,Raj,UAE,Salalah,Speaker,75.0,1.0,75.0,15.0
4274,4271.0,26-Aug-2021,35.0,Chrismas Coupon,Cash,Ramzan,India,Muscat,Keyboard,100.0,1.0,100.0,10.0

In [27]:
# Filling missing values
data['Sales_fillNA']=data['Sales'].fillna(data['Sales'].mean())

In [28]:
data

,No,Transaction Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit,Sales_fillNA
0,1.0,01-Jan-2010,37.0,Black Friday,Cash,Ramzan,UAE,Dubai,Mobile,1200.0,3.0,3600.0,200.0,3600.0
1,2.0,02-Jan-2010,40.0,Chrismas Coupon,Visa Card,Kumayl,India,Abu Dhabi,Laptop,4500.0,2.0,9000.0,250.0,9000.0
2,3.0,03-Jan-2010,36.0,Loyalty Coupon,Master Card,John,Oman,NaN,Moniter,3000.0,2.0,6000.0,300.0,6000.0
3,4.0,03-Jan-2010,46.0,Black Friday,Stripe,Abdullah,UAE,NaN,Speaker,75.0,1.0,75.0,15.0,75.0
4,5.0,03-Jan-2010,24.0,Chrismas Coupon,Cheque,David,India,NaN,Keyboard,100.0,3.0,300.0,10.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,4267.0,26-Aug-2021,63.0,Black Friday,Visa Card,Abdullah,UAE,Muscat,Mobile,1200.0,2.0,2400.0,200.0,2400.0
4271,4268.0,26-Aug-2021,64.0,Chrismas Coupon,Master Card,David,India,Salalah,Laptop,4500.0,3.0,13500.0,250.0,13500.0
4272,4269.0,26-Aug-2021,27.0,Loyalty Coupon,Stripe,Nancy,Oman,Muscat,Moniter,3000.0,3.0,9000.0,300.0,9000.0
4273,4270.0,26-Aug-2021,20.0,Black Friday,Cheque,Raj,UAE,Salalah,Speaker,75.0,1.0,75.0,15.0,75.0
4274,4271.0,26-Aug-2021,35.0,Chrismas Coupon,Cash,Ramzan,India,Muscat,Keyboard,100.0,1.0,100.0,10.0,100.0

In [29]:
data.isnull().sum()

No                   4
Transaction Date     4
Customer Age         4
Coupon Type          4
Payment Method       6
Sales Person        12
Country              4
City                 7
Product             22
Price                4
Units                4
Sales                4
Profit               4
Sales_fillNA         0
dtype: int64

In [30]:
data.dtypes

No                  float64
Transaction Date     object
Customer Age        float64
Coupon Type          object
Payment Method       object
Sales Person         object
Country              object
City                 object
Product              object
Price               float64
Units               float64
Sales               float64
Profit              float64
Sales_fillNA        float64
dtype: object

In [32]:
# Rename Columns
data.rename(columns={'Transaction Date':'Sales Date'})

,No,Sales Date,Customer Age,Coupon Type,Payment Method,Sales Person,Country,City,Product,Price,Units,Sales,Profit,Sales_fillNA
0,1.0,01-Jan-2010,37.0,Black Friday,Cash,Ramzan,UAE,Dubai,Mobile,1200.0,3.0,3600.0,200.0,3600.0
1,2.0,02-Jan-2010,40.0,Chrismas Coupon,Visa Card,Kumayl,India,Abu Dhabi,Laptop,4500.0,2.0,9000.0,250.0,9000.0
2,3.0,03-Jan-2010,36.0,Loyalty Coupon,Master Card,John,Oman,NaN,Moniter,3000.0,2.0,6000.0,300.0,6000.0
3,4.0,03-Jan-2010,46.0,Black Friday,Stripe,Abdullah,UAE,NaN,Speaker,75.0,1.0,75.0,15.0,75.0
4,5.0,03-Jan-2010,24.0,Chrismas Coupon,Cheque,David,India,NaN,Keyboard,100.0,3.0,300.0,10.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4270,4267.0,26-Aug-2021,63.0,Black Friday,Visa Card,Abdullah,UAE,Muscat,Mobile,1200.0,2.0,2400.0,200.0,2400.0
4271,4268.0,26-Aug-2021,64.0,Chrismas Coupon,Master Card,David,India,Salalah,Laptop,4500.0,3.0,13500.0,250.0,13500.0
4272,4269.0,26-Aug-2021,27.0,Loyalty Coupon,Stripe,Nancy,Oman,Muscat,Moniter,3000.0,3.0,9000.0,300.0,9000.0
4273,4270.0,26-Aug-2021,20.0,Black Friday,Cheque,Raj,UAE,Salalah,Speaker,75.0,1.0,75.0,15.0,75.0
4274,4271.0,26-Aug-2021,35.0,Chrismas Coupon,Cash,Ramzan,India,Muscat,Keyboard,100.0,1.0,100.0,10.0,100.0

In [36]:
# change the data type
data['Units']=data['Units'].fillna(data['Units'].mean()).astype(int)

In [37]:
data.dtypes

No                  float64
Transaction Date     object
Customer Age        float64
Coupon Type          object
Payment Method       object
Sales Person         object
Country              object
City                 object
Product              object
Price               float64
Units                 int32
Sales               float64
Profit              float64
Sales_fillNA        float64
dtype: object

In [38]:
data['New Price']=data['Price'].apply(lambda x:x*2)

In [42]:
# modify the existing price data
print(data[['Price', 'New Price']].head())

    Price  New Price
0  1200.0     2400.0
1  4500.0     9000.0
2  3000.0     6000.0
3    75.0      150.0
4   100.0      200.0

In [44]:
# aggregating and grouping
grouped_mean = data.groupby('Product')['Sales_fillNA'].mean()
print(grouped_mean)

Product
Hard Disk        704.327808
Keyboard         182.897603
Laptop          7528.838174
Mobile          2136.263736
Moniter         5222.103004
Mother Board    8233.407080
Mouse             90.198238
RAM              444.791667
Speaker          155.735931
Name: Sales_fillNA, dtype: float64

In [47]:
data.groupby(['Product','Coupon Type'])['Sales_fillNA'].sum()

Product       Coupon Type
Hard Disk     Black Friday        133675.0
              Chrismas Coupon     199600.0
              Loyalty Coupon       49175.0
Keyboard      Black Friday           250.0
              Chrismas Coupon      83600.0
              Loyalty Coupon         100.0
Laptop        Black Friday         10625.0
              Chrismas Coupon    3605100.0
              Loyalty Coupon       13175.0
Mobile        Black Friday        972000.0
Moniter       Black Friday          2750.0
              Chrismas Coupon      18300.0
              Loyalty Coupon     2412450.0
Mother Board  Chrismas Coupon    3721500.0
Mouse         Loyalty Coupon       40950.0
RAM           Black Friday          5675.0
              Chrismas Coupon      50000.0
              Loyalty Coupon      157825.0
Speaker       Black Friday         62175.0
              Chrismas Coupon       9100.0
              Loyalty Coupon         675.0
Name: Sales_fillNA, dtype: float64

In [48]:
data.groupby(['Product','Coupon Type'])['Sales_fillNA'].mean()

Product       Coupon Type
Hard Disk     Black Friday        276.759834
              Chrismas Coupon    6438.709677
              Loyalty Coupon     1695.689655
Keyboard      Black Friday        250.000000
              Chrismas Coupon     182.932166
              Loyalty Coupon      100.000000
Laptop        Black Friday       1180.555556
              Chrismas Coupon    7769.612069
              Loyalty Coupon     1463.888889
Mobile        Black Friday       2136.263736
Moniter       Black Friday        916.666667
              Chrismas Coupon    6100.000000
              Loyalty Coupon     5244.456522
Mother Board  Chrismas Coupon    8233.407080
Mouse         Loyalty Coupon       90.198238
RAM           Black Friday        630.555556
              Chrismas Coupon    5555.555556
              Loyalty Coupon      341.612554
Speaker       Black Friday        135.753275
              Chrismas Coupon    4550.000000
              Loyalty Coupon      337.500000
Name: Sales_fillNA, dtype: float64

In [50]:
grouped_agg = data.groupby('Coupon Type')['Sales_fillNA'].agg(['mean','sum','count'])
print(grouped_agg)

                        mean        sum  count
Coupon Type
Black Friday      836.709972  1191475.0   1424
Chrismas Coupon  5426.966292  7728000.0   1424
Loyalty Coupon   1892.691497  2693300.0   1423

In [52]:
# merging and joining dataframes
df1 = pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value1':[4,5,6]})
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [53]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [55]:
# Merge Dataframes on the key columns
pd.merge(df1,df2,on="Key",how="inner")

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [56]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [57]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [58]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6